spring.application.name=Api-Gateway
server.port=8765

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true




# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# USER SERVICE
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

# BOOKING SERVICE
spring.cloud.gateway.routes[2].id=booking-service
spring.cloud.gateway.routes[2].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/booking/**

# TRAIN SERVICE
spring.cloud.gateway.routes[3].id=train-service
spring.cloud.gateway.routes[3].uri=lb://TRAIN-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/train/**

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=192.168.1.10
eureka.instance.prefer-ip-address=true

