spring.application.name=Payment-Service

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/PaymentService
spring.datasource.username=root
spring.datasource.password=Admin

# DRIVER AND DIALECT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JPA SETTINGS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER PORT
server.port=8095

# Eureka client configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Health check via Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=192.168.1.10
eureka.instance.prefer-ip-address=true

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG



# Razorpay keys (TEST mode)
razorpay.key_id=rzp_test_VAaVzANxZmxJeN
razorpay.key_secret=67OpVyksMFzlLpdgo7kampIv
razorpay.currency=INR
# 1 = auto-capture, 0 = auth-only
razorpay.payment_capture=1

# Razorpay Webhook secret (same value jo dashboard ? Webhooks ? Secret field me dala hai)
razorpay.webhook-secret=MySecret

# Spring settings
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false


spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username =saqibansari2011@gmail.com
spring.mail.password =wgkr kovn frrz dkpn
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

logging.level.com.saqib.Payment_Service.feign=DEBUG

app.skip-signature-check=true

#jwt.secret=YXBpLWdwdC1qc29uLXNlY3VyZS1zZWNyZXQta2V5LWZvci1qc29uLXRva2Vu

